name: dev_pull_closed

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: dev
    - name: Send Payload
      run: |
        curl -X POST ${{ secrets.OCP_URL }}/apis/build.openshift.io/v1/namespaces/dbc-bcdc-tools/buildconfigs/bcdc-ckan-ext-cicd/webhooks/${{ secrets.OCP_WEBHOOK_DEV }}/generic
